development:
  adapter: mysql2
  encoding: utf8
  database: titan_clan
  host: test.c5729kvnntur.us-east-1.rds.amazonaws.com
  username: masteruser
  password: masteruser
  # database: titan_clan
  # host: 127.0.0.1
  # username: root
  # password: root
  socket: /tmp/mysql.sock
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: titan_clan
  host: 127.0.0.1
  username: root
  password: root
  socket: /tmp/mysql.sock
  reconnect: true
  
test:
  adapter: mysql2
  encoding: utf8
  database: titan_clan
  host: 127.0.0.1
  username: root
  password: root
  socket: /tmp/mysql.sock
  reconnect: true